from django.contrib import admin
from .models import *
# Register your models here.

admin.site.register(Cities)
admin.site.register(AddressType)
admin.site.register(Areas)
admin.site.register(District)
admin.site.register(Street)
admin.site.register(ClientCategory)
admin.site.register(CategoryType)
admin.site.register(WorkType)
admin.site.register(TransactionType)
admin.site.register(Status)
admin.site.register(SectorEcon)
admin.site.register(ProjectType)
admin.site.register(PositionType)
admin.site.register(PeriodType)
admin.site.register(PaymentType)
admin.site.register(OrgForm)
admin.site.register(LinkType)
admin.site.register(LineType)
admin.site.register(IdcardType)
admin.site.register(FormProperty)
admin.site.register(Currencies)
admin.site.register(CreditTarget)
admin.site.register(CreditSource)
admin.site.register(Country)
admin.site.register(Counters)
admin.site.register(ContactType)
admin.site.register(CollateralType)
admin.site.register(DeptType)
admin.site.register(Bank)
admin.site.register(Calculate)
admin.site.register(BaseAccount)
admin.site.register(AccountPattern)
admin.site.register(AccountType)
admin.site.register(Departament)
admin.site.register(PaymentRule)
admin.site.register(CreditType)
admin.site.register(InterestScheme)
admin.site.register(InterestRate)
admin.site.register(InterestJournal)
admin.site.register(Insurance)
admin.site.register(InsuranceLink)
